apiVersion: apps/v1
kind: Deployment
metadata:
  name: bol-mancala
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bol-mancala
  template:
    metadata:
      labels:
        app: bol-mancala
    spec:
      containers:
        - name: bol-mancala-image
          image: europe-central2-docker.pkg.dev/bol-mancala-345402/bol-mancala-repo/bol-mancala-image:b6752a41d7d6986105f96ff0aee1e002756f5462
