apiVersion: apps/v1
kind: Deployment
metadata:
  name: bol-mancala
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: bol-mancala
    spec:
      containers:
        - name: bol-mancala
          image: registry.gitlab.com/rafay-habibullah/bol-mancala
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: registry.gitlab.com