apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bol-mancala
  name: bol-mancala
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: bol-mancala
  type: LoadBalancer
status:
  loadBalancer: {}
